services:
  central-db:
    ports:
      - "5432:5432"

  central-api:
    ports:
      - "8080:8080"
    environment:
      CORS_ORIGIN: http://localhost:8088

  dashboard:
    ports:
      - "8088:80"
