ALTER TABLE facility_daily_summaries
  ADD COLUMN IF NOT EXISTS ncd_dm_patients INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ncd_ht_patients INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ncd_dm_ht_patients INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ncd_bp_screened INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ncd_fbs_screened INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missing_diagnosis INTEGER NOT NULL DEFAULT 0;
